DAY 2 ASSIGNMENT

PART-A

In [1]:
import numpy as np

1. Generate a 1D NumPy array containing numbers from 0 to 9.

In [4]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


2. Reshape a 1D array into a 2D array

In [20]:
arr_1 = np.arange(20)#1DIMENSIONAL ARRAY
print(arr_1) 

arr_2 = arr_1.reshape(2,10) #RESHAPE INTO 2 DIMENSIONAL ARRAY
print(arr_2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


3. Perform element-wise addition and multiplication of two matrices - Compute the dot
product of two compatible matrices- Transpose a given matrix and verify the result.

In [28]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[5,6,4],[8,9,7],[6,3,2]])
print(A+B)
print(np.dot(A,B))
print(np.transpose(A))

[[ 6  8  7]
 [12 14 13]
 [13 11 11]]
[[ 39  33  24]
 [ 96  87  63]
 [153 141 102]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


4. Extract elements that satisfy a certain condition (e.g., elements greater than 5) -
Replace all negative values in an array with zero.

In [30]:
arr_3 = np.array([1, 3, 5, 7, 9])

# Extract elements greater than 5
greater_than_5 = arr[arr > 5]

print("Elements greater than 5:", greater_than_5)


Elements greater than 5: [7 9]


In [34]:
arr_4 = np.array([1, -3, 5, -7, 9])
arr_4[arr_4<0]=0
print(arr_4)

[1 0 5 0 9]


5. Reverse the order of elements in a 1D array

In [40]:
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)


Reversed array: [5 4 3 2 1]


6. Compute the
mean, median, and standard deviation

In [41]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

3.0
3.0
1.4142135623730951


7. Save a NumPy array to a .npy file and load it back.

In [45]:
array = np.array([[1, 2, 3], [4, 5, 6]])
np.save('my_array.npy', array)

loaded_array = np.load('my_array.npy')

print("Loaded Array:",loaded_array)


Loaded Array: [[1 2 3]
 [4 5 6]]


8. Export a 2D array to a CSV file using np.savetxt and read it
using np.loadtxt

In [52]:
array = np.array([[10, 20, 30], [40, 50, 60]])
np.savetxt('my_array.csv', array, delimiter=',', fmt='%d')
loaded_array = np.loadtxt('my_array.csv', delimiter=',')
print(loaded_array)

[[10. 20. 30.]
 [40. 50. 60.]]


9. Merge two arrays horizontally.

In [49]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.hstack((a, b))

print(c)


[[1 2 5 6]
 [3 4 7 8]]
