In [11]:
import numpy as np

In [12]:
expenses = np.array([[2,5,8],[8,6,7]])
print(expenses)
#adding 2 with all elements
print(expenses+2)

#taking square root
print(np.sqrt(expenses))

#taking square 
print(expenses**2)

[[2 5 8]
 [8 6 7]]
[[ 4  7 10]
 [10  8  9]]
[[1.41421356 2.23606798 2.82842712]
 [2.82842712 2.44948974 2.64575131]]
[[ 4 25 64]
 [64 36 49]]


In [13]:
exp_jan = np.array([10,60])
exp_feb = np.array([50,96])
exp_total = exp_jan+exp_feb
print(exp_total)

[ 60 156]




LIST

In [14]:
my_list=[1,"kiruba",4.5]
print(my_list)

my_list.append(4)  #TO ADD A VALUE
print(my_list)

my_list.remove(4) #TO REMOVE A VALUE
print(my_list)  

print(len(my_list)) #TO FIND THE LENGTH OF THE LIST

print(my_list[2])  


[1, 'kiruba', 4.5]
[1, 'kiruba', 4.5, 4]
[1, 'kiruba', 4.5]
3
4.5


In [15]:
order=["LAPTOP",1,"ELECTRONICS",9999.0]
print("Initial order",order)

order.append("Mouse")#ADD ANOTHER PRODUCT i.e)MOUSE
print("Updated order",order)

order.remove("Mouse")
print("Final order",order)

Initial order ['LAPTOP', 1, 'ELECTRONICS', 9999.0]
Updated order ['LAPTOP', 1, 'ELECTRONICS', 9999.0, 'Mouse']
Final order ['LAPTOP', 1, 'ELECTRONICS', 9999.0]


ARRAY

In [16]:
my_array = np.array([1,2,3])
print(my_array.shape)
print(my_array[1])

(3,)
2


In [17]:
my_array_1 = np.array([[1],[2],[3]])
print(my_array_1.shape)

(3, 1)




ARRAY TO MATRIX

In [18]:
matrix=np.array([[1,6],[2,6]])
print(matrix)
print(np.transpose(matrix))


[[1 6]
 [2 6]]
[[1 2]
 [6 6]]


In [19]:
A=np.array([[5,8],[5,8]])
B=np.array([[1,6],[2,6]])
print(A)
print(B)
print(A+B)
print(np.dot(A,B))

[[5 8]
 [5 8]]
[[1 6]
 [2 6]]
[[ 6 14]
 [ 7 14]]
[[21 78]
 [21 78]]


In [20]:
array_1=np.arange(0,20,4) # arange(Start, stop, step)
print(array_1)

[ 0  4  8 12 16]


In [22]:
array_2=np.linspace(0,10,4) # arange(Start, stop, step)
print(array_2)

[ 0.          3.33333333  6.66666667 10.        ]





INITIALIZING A ARRAY WITH ONES AND ZEROS

In [34]:
array_2 = np.zeros((4,10))# 4 rows and 10 columns
print(array_2)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [26]:
array_3 = np.ones((4,10))# 4 rows and 10 columns
print(array_3)
print(array_3*12)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12. 12. 12. 12. 12. 12.]]




RANDOM NUMBERS WITH NUMPY

In [33]:
rand_num=np.random.rand(5)# to create 5 uniform random numbers(0,1)
print(rand_num)

rand_num=np.random.randn(10)
print(rand_num)


[0.79747597 0.23947136 0.62409697 0.11557614 0.4083104 ]
[ 1.83612148 -1.8688173   0.13239522 -0.25220668  0.11691044  0.93759586
 -1.4232329  -1.1154532  -0.67850377  0.13154249]


In [38]:
distance = np.array([2.5, 1.8, 3.2, 0.9, 4.1])
fuel_cost=distance*0.5
print("Total Cost",fuel_cost.sum())
print("Average Cost",fuel_cost.mean())

Total Cost 6.25
Average Cost 1.25


In [37]:
distance_1= np.array([2.5, 1.8, 3.2, 0.9])
fuel_cost_1=distance_1*0.5
print("Total Cost",fuel_cost_1.sum())
print("Average Cost",fuel_cost_1.mean())

Total Cost 4.2
Average Cost 1.05


In [46]:
from numpy import random

x = random.randint(100)
print(x)

54
